export default {
    CREATE_TODO_ITEM: 'CREATE_TODO_ITEM',
    EDIT_STATUS_TODO_ITEM: 'EDIT_STATUS_TODO_ITEM',
    EDIT_TODO_ITEM: 'EDIT_TODO_ITEM',
    REMOVE_TODO_ITEM: 'REMOVE_TODO_ITEM',
    SET_TODO_STATUS_FILTER: 'SET_TODO_STATUS_FILTER',
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_INCOMPLETED: 'SHOW_INCOMPLETED',
};